-- CreateTable
CREATE TABLE "Users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "salt" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Capteur" (
    "DevEUI" TEXT NOT NULL PRIMARY KEY,
    "AppEUI" TEXT NOT NULL,
    "IdCapteurType" TEXT NOT NULL,
    "Description" TEXT,
    "Commentaire" TEXT,
    "Name" TEXT NOT NULL,
    "LowBattery" BOOLEAN NOT NULL DEFAULT false,
    "CreatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Capteur_IdCapteurType_fkey" FOREIGN KEY ("IdCapteurType") REFERENCES "CapteurType" ("Id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CapteurType" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Type" TEXT NOT NULL,
    "ModelName" TEXT NOT NULL,
    "Module" TEXT NOT NULL,
    "CreatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "ReleverCapteur" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "DevEUI" TEXT NOT NULL,
    "Value" REAL,
    "ValueRaw" REAL NOT NULL,
    "ValueType" TEXT,
    "ValueTypeRaw" TEXT,
    "Time" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ReleverCapteur_DevEUI_fkey" FOREIGN KEY ("DevEUI") REFERENCES "Capteur" ("DevEUI") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Site" (
    "Id" TEXT NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "CreatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "SiteHasCapteur" (
    "IdSite" TEXT NOT NULL,
    "DevEUI" TEXT NOT NULL,
    "Commentaire" TEXT,
    "CreatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("IdSite", "DevEUI"),
    CONSTRAINT "SiteHasCapteur_IdSite_fkey" FOREIGN KEY ("IdSite") REFERENCES "Site" ("Id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "SiteHasCapteur_DevEUI_fkey" FOREIGN KEY ("DevEUI") REFERENCES "Capteur" ("DevEUI") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Users_email_key" ON "Users"("email");
